# Generated by Django 6.0.2 on 2026-04-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='decors'),
        ),
    ]
