# Generated by Django 6.0.2 on 2026-04-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_decor_description_decor_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decor',
            old_name='image_url',
            new_name='image',
        ),
    ]
